apiVersion: apps/v1
kind: Deployment
# 1) metadata
metadata:
  name: nginx-deployment
  labels:
    app: nginx
# 2) specification
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 8080
